<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2017
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

$GLOBALS['TL_LANG']['pct_device'][0] = 'Endgeräte-Sichtbarkeit';
$GLOBALS['TL_LANG']['pct_device'][1] = 'Wählen Sie den Endgerätetyp auf dem das Element angezeigt werden soll.';	
$GLOBALS['TL_LANG']['pct_device_ref'][1] = 'Nur mobile Endgeräte';
$GLOBALS['TL_LANG']['pct_device_ref'][2] = 'Nur Desktop-Endgeräte';
